### ISSUE TITLE
Add "hide targets with no description" setting

### ISSUE THREAD

**Issue by gene-pavlovsky** [SlavaRa/fdplugin-antpanel#26]
Running `ant -projecthelp` lists only targets that have the description attribute set (unless none of the targets have a description, then all targets are listed). This allows to "hide" internal targets (e.g. `init` or `check.build.uptodate`). It would be nice to have that setting in AntPanel.
Of course, I can name targets starting with a minus e.g. `-internal.target` and it won't show in either `ant -projecthelp` or AntPanel, but when running ant those targets still print some output and that minus is not pretty to look at.

**Comment by SlavaRa** [comment]
Если честно, не совсем уловил фишку(( видимо уже сплю совсем, может по русски?

**Comment by gene-pavlovsky** [comment]
В build file есть targets, которые как бы private, т.е. не предполагается, что юзер их будет сам запускать, вызываются они только через depends или antcall. Можно, конечно, их скрывать, добавив "-" в начале названия. 
Но неплохо было бы сделать ещё и скрытие target-ов, у которых нету или пустой description. Так работает опция ant -projecthelp - показывает только target-ы с описанием.
Т.е. логика такая
Если есть хоть один target с description, то показывать в списке только target-ы c description, иначе все (кроме тех, что начинаются на `-`).

**Comment by SlavaRa** [comment]
хм.. я могу добавить такой сеттинг, мне не сложно.. хотя по мне это все очень странно ще вчера было. могу сделать в выходные/на след. неделе

**Comment by gene-pavlovsky** [comment]
Фичу могу, наверно, и сам сделать... Только не пойму, как мне настроить компиляцию. Visual Studio пользовался пару раз только, как раз что-то делал по FlashDevelop-у. У меня, стало быть, скачан с git FlashDevelop и antpanel. Но antpanel ругается, что не может найти PluginCore и т.п. Где-то надо добавить classpath или reference или как там это называется, что -то не найду я. Подскажешь?

**Comment by SlavaRa** [comment]
https://github.com/SlavaRa/flashdevelop-plugins/tree/feature/Plugins

**Comment by SlavaRa** [comment]
или заглянуть сюда https://github.com/SlavaRa/fdplugin-antpanel/blob/master/appveyor.yml
