### ISSUE TITLE
Add support for themes

### ISSUE THREAD

**Issue by SlavaRa** [SlavaRa/fdplugin-antpanel#28]

**Comment by gene-pavlovsky** [comment]
![fd-ant-panel](https://cloud.githubusercontent.com/assets/2841193/14425095/656cdbaa-ffed-11e5-88bb-dda6f5a98e6d.png)
Already looks good, no?

**Comment by SlavaRa** [comment]
What about ContextMenu?

**Comment by gene-pavlovsky** [comment]
Ah, I missed that. I only use double-click or enter to run targets.

**Comment by gene-pavlovsky** [comment]
Installed the latest release fdz, I can't see any changes for some reason. Perhaps I need to install the latest FD dev build?

**Comment by SlavaRa** [comment]
Check this https://ci.appveyor.com/project/slavara/fd-antpanel-plugin

**Comment by gene-pavlovsky** [comment]
This appveyor service is very cool...
Got the latest release, the menu still looks same as before.

**Comment by gene-pavlovsky** [comment]
Installed https://github.com/SlavaRa/fdplugin-antpanel/releases/tag/2.0.110
(Deleted plug-in, verified it's not present, reinstalled)
![ant-panel-cm](https://cloud.githubusercontent.com/assets/2841193/14507039/836458b2-01c9-11e6-9d39-7bca3ec0c686.png)

**Comment by SlavaRa** [comment]
Завтра посмотрю, я гуляю))

**Comment by gene-pavlovsky** [comment]
Enjoy!

**Comment by gene-pavlovsky** [comment]
Verified.
